template: Hello, %s!
defaultName: Stranger

# the key needs to match the suffix of the renderer
viewRendererConfiguration:
    .ftl:
        strict_syntax: yes
        whitespace_stripping: yes

database:
    driverClass: org.sqlite.JDBC
    url: jdbc:sqlite:weather.db
    properties:
        hibernate.dialect: org.hibernate.dialect.SQLiteDialect
        hibernate.show_sql: true
sundial:
    thread-pool-size: 10
    shutdown-on-unload: true
    wait-on-shutdown: false
    start-delay-seconds: 0
    start-scheduler-on-load: true
    global-lock-on-load: false
    annotated-jobs-package-name: com.qprogramming.weather.jobs
dataFile: data.csv    